server:
  port: 9000
  max-http-header-size: 16KB

spring:
  application:
    name: gateway
  redis:
    # Redis数据库索引（默认为0）
    database: 6
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
  security:
    csrf:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.14:8848
        username: yss
        password: 123
    gateway:
      routes:
        - id: school-server
          uri: lb://school-server
          predicates:
            - Path=/school/**
          filters:
            - RewritePath=/school/(?<segment>.*),/$\{segment}
        - id: uaa-server
          uri: lb://uaa-server
          predicates:
            - Path=/uaa/**
          filters:
            - RewritePath=/uaa/(?<segment>.*), /${segment}
        - id: work-server
          uri: lb://work-server
          predicates:
            - Path=/work/**
          filters:
            - RewritePath=/work/(?<segment>.*),/$\{segment}
        - id: base-server
          uri: lb://base-service
          predicates:
            - Path=/base/**
          filters:
            - RewritePath=/base/(?<segment>.*),/$\{segment}